image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew
    - ./gradlew test -Dselenide.headless=true --info